FROM arm32v7/node:12-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

COPY app.js app.js
COPY lib lib
COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm i --production

CMD npm start
